#!/usr/bin/env python3
"""
build_journal.py — Journal build system for wilrandolph.com
============================================================

posts.json is the single source of truth for all journal content.

WORKFLOW TO PUBLISH A NEW POST:
  1. Open posts.json and add a new post object at the TOP of the array
     (newest first). Follow the structure of the existing entries:

     {
       "id": "unique-slug-no-spaces",
       "title": "Your Post Title",
       "date": "2026-01-15",
       "dateDisplay": "January 15, 2026",
       "categories": ["Brand Strategy", "Leadership"],
       "image": "https://your-image-url.jpg",
       "excerpt": "One or two sentence summary of the post.",
       "body": "<p>Full HTML body. Use <h3> for subheads, <p> for paragraphs.</p>"
     }

  2. Run:  python3 build_journal.py
     This regenerates:
       - journal/<id>.html      one shareable permalink page per post,
                                with Open Graph / Twitter Card meta so
                                LinkedIn, X, and Facebook render rich previews
       - the POSTS data block inside journal.html (between POSTS:BEGIN/END)
       - the OG meta block inside journal.html (latest post drives og:image)

  3. Commit and push to GitHub — Vercel deploys automatically.

Never edit journal/<id>.html or the marked blocks in journal.html by hand;
the next build overwrites them.
"""

import json
import html
import re
import sys
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent
SITE_URL = "https://www.wilrandolph.com"
JOURNAL_DIR = ROOT / "journal"
FINGERPRINT = "<!-- generated by build_journal.py — do not edit by hand -->"

# ── SVG icons (fill: currentColor, 24x24 viewBox) ────────────────────────────
ICONS = {
    "linkedin": '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.225 0z"/></svg>',
    "x": '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M18.901 1.153h3.68l-8.04 9.19L24 22.846h-7.406l-5.8-7.584-6.638 7.584H.474l8.6-9.83L0 1.154h7.594l5.243 6.932ZM17.61 20.644h2.039L6.486 3.24H4.298Z"/></svg>',
    "facebook": '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/></svg>',
    "email": '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 12.713L.015 4.042A1.994 1.994 0 0 1 2 2.25h20c1.03 0 1.877.78 1.985 1.792L12 12.713zM12 15.187L0 6.5V19.75c0 1.105.895 2 2 2h20c1.105 0 2-.895 2-2V6.5l-12 8.687z"/></svg>',
    "link": '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M13.06 8.11l1.415 1.415a7 7 0 0 1 0 9.9l-.354.353a7 7 0 0 1-9.9-9.9l1.415 1.415a5 5 0 1 0 7.071 7.071l.354-.354a5 5 0 0 0 0-7.07l-1.415-1.415 1.415-1.414zm6.718 6.011l-1.414-1.414a5 5 0 1 0-7.071-7.071l-.354.354a5 5 0 0 0 0 7.07l1.415 1.415-1.415 1.414-1.414-1.414a7 7 0 0 1 0-9.9l.354-.353a7 7 0 0 1 9.9 9.9z"/></svg>',
}


def esc(s: str) -> str:
    return html.escape(s, quote=True)


def post_url(post: dict) -> str:
    return f"{SITE_URL}/journal/{post['id']}.html"


def share_bar(post: dict) -> str:
    """Share links that pass this post's unique permalink to each network."""
    url = post_url(post)
    u = quote(url, safe="")
    t = quote(post["title"], safe="")
    body = quote(f"{post['excerpt']}\n\n{url}", safe="")
    return (
        '<div class="wr-share">'
        '<span class="wr-share-label">Share</span>'
        f'<a href="https://www.linkedin.com/sharing/share-offsite/?url={u}" target="_blank" rel="noopener" aria-label="Share on LinkedIn">{ICONS["linkedin"]}LinkedIn</a>'
        f'<a href="https://twitter.com/intent/tweet?url={u}&amp;text={t}" target="_blank" rel="noopener" aria-label="Share on X">{ICONS["x"]}X</a>'
        f'<a href="https://www.facebook.com/sharer/sharer.php?u={u}" target="_blank" rel="noopener" aria-label="Share on Facebook">{ICONS["facebook"]}Facebook</a>'
        f'<a href="mailto:?subject={t}&amp;body={body}" aria-label="Share by email">{ICONS["email"]}Email</a>'
        f'<button type="button" class="wr-copy-btn" data-url="{esc(url)}">{ICONS["link"]}<span>Copy Link</span></button>'
        "</div>"
    )


def json_ld(post: dict) -> str:
    data = {
        "@context": "https://schema.org",
        "@type": "BlogPosting",
        "headline": post["title"],
        "description": post["excerpt"],
        "image": post["image"],
        "datePublished": post["date"],
        "author": {"@type": "Person", "name": "Wil Randolph", "url": SITE_URL},
        "publisher": {"@type": "Person", "name": "Wil Randolph"},
        "mainEntityOfPage": post_url(post),
    }
    return json.dumps(data, indent=2).replace("</", "<\\/")


def cat_tags(post: dict) -> str:
    return "".join(f'<span class="wr-cat-tag">{esc(c)}</span>' for c in post["categories"])


PAGE_CSS = """
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{
  --ink:#0f0e0c;--ink-muted:#4a4844;--ink-faint:#9a9690;
  --paper:#faf8f5;--paper-warm:#f2ede6;--paper-mid:#e8e2d9;
  --gold:#c9a84c;--gold-light:#e8d49a;--gold-muted:#8b6e2a;
  --charcoal:#0a0a0e;
  --font-display:'Cormorant Garamond',Georgia,serif;
  --font-body:'DM Sans',sans-serif;
  --font-mono:'DM Mono',monospace;
  --ease-out:cubic-bezier(0.16,1,0.3,1);
}
html{scroll-behavior:smooth}
body{font-family:var(--font-body);background:var(--charcoal);color:var(--paper);overflow-x:hidden}

/* ─── NAV ─── */
#wr-nav{
  position:fixed;top:0;left:0;right:0;z-index:9999;
  display:flex;align-items:center;justify-content:space-between;
  padding:28px 56px;
  background:rgba(10,10,14,0.97);
  backdrop-filter:blur(20px);
  border-bottom:1px solid rgba(255,255,255,0.06);
}
.wr-nav-brand{text-decoration:none;display:flex;flex-direction:column;gap:3px}
.wr-nav-name{font-family:var(--font-display);font-size:22px;font-weight:300;color:#fff;line-height:1.1;letter-spacing:0.02em}
.wr-nav-sub{font-family:var(--font-mono);font-size:9px;letter-spacing:0.22em;text-transform:uppercase;color:rgba(255,255,255,0.4)}
.wr-nav-links{display:flex;align-items:center;gap:28px}
.wr-nav-links a{font-family:var(--font-mono);font-size:11px;letter-spacing:0.18em;text-transform:uppercase;color:rgba(255,255,255,0.7);text-decoration:none;transition:color 0.25s;white-space:nowrap}
.wr-nav-links a:hover{color:#fff}
.wr-nav-links a.active{color:var(--gold)}
.wr-nav-div{display:block;width:1px;height:18px;background:var(--gold);opacity:0.5;flex-shrink:0}
@media(max-width:860px){.wr-nav-links{display:none}#wr-nav{padding:20px 28px}}

/* ─── PROGRESS ─── */
#wr-progress{position:fixed;top:0;left:0;height:2px;background:var(--gold);width:0%;z-index:9999;transition:width 0.1s linear}

/* ─── ARTICLE ─── */
#wr-article{max-width:820px;margin:0 auto;padding:170px 32px 0}
.wr-back{
  display:inline-flex;align-items:center;gap:10px;
  font-family:var(--font-mono);font-size:9px;letter-spacing:0.2em;
  text-transform:uppercase;color:rgba(250,248,245,0.35);
  text-decoration:none;margin-bottom:36px;transition:color 0.25s;
}
.wr-back::before{content:'';display:block;width:24px;height:1px;background:var(--gold);opacity:0.6}
.wr-back:hover{color:var(--gold)}
.wr-article-cats{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:22px}
.wr-cat-tag{
  font-family:var(--font-mono);font-size:8px;letter-spacing:0.18em;
  text-transform:uppercase;padding:4px 12px;
  border:1px solid rgba(201,168,76,0.25);
  color:rgba(201,168,76,0.7);border-radius:2px;
}
.wr-article-title{
  font-family:var(--font-display);font-weight:300;
  font-size:clamp(34px,4.6vw,54px);line-height:1.08;
  color:var(--paper);letter-spacing:-0.01em;margin-bottom:22px;
}
.wr-article-meta{
  font-family:var(--font-mono);font-size:9px;letter-spacing:0.14em;
  text-transform:uppercase;color:rgba(250,248,245,0.3);
  display:flex;align-items:center;gap:14px;margin-bottom:28px;
}
.wr-meta-dot{width:3px;height:3px;border-radius:50%;background:rgba(201,168,76,0.4)}

/* ─── SHARE ─── */
.wr-share{display:flex;align-items:center;flex-wrap:wrap;gap:10px}
.wr-share-label{
  font-family:var(--font-mono);font-size:8px;letter-spacing:0.22em;
  text-transform:uppercase;color:rgba(250,248,245,0.3);margin-right:4px;
}
.wr-share a,.wr-share button{
  display:inline-flex;align-items:center;gap:7px;
  font-family:var(--font-mono);font-size:9px;letter-spacing:0.14em;
  text-transform:uppercase;color:rgba(250,248,245,0.55);text-decoration:none;
  border:1px solid rgba(255,255,255,0.12);background:transparent;
  padding:7px 14px;border-radius:2px;cursor:pointer;transition:all 0.25s;
}
.wr-share a:hover,.wr-share button:hover{border-color:rgba(201,168,76,0.5);color:var(--gold)}
.wr-share svg{width:12px;height:12px;fill:currentColor;display:block;flex-shrink:0}
.wr-article-head .wr-share{padding-bottom:36px;border-bottom:1px solid rgba(255,255,255,0.06)}

/* ─── HERO ─── */
.wr-article-hero{margin:44px 0 48px;border-radius:2px;overflow:hidden;background:#111}
.wr-article-hero img{width:100%;max-height:480px;object-fit:cover;display:block;filter:brightness(0.8)}

/* ─── BODY ─── */
.wr-article-body{font-size:16px;line-height:1.95;color:rgba(250,248,245,0.68);font-weight:300}
.wr-article-body h3{
  font-family:var(--font-display);font-size:26px;font-weight:600;
  color:var(--paper);margin:40px 0 16px;line-height:1.2;
}
.wr-article-body p{margin-bottom:22px}
.wr-article-body p:last-child{margin-bottom:0}
.wr-article-body em{font-style:italic;color:rgba(250,248,245,0.88)}
.wr-article-body strong{color:rgba(250,248,245,0.92);font-weight:400}
.wr-article-body img{width:100%;margin:32px 0;display:block;border-radius:2px;filter:brightness(0.88)}

/* ─── FOOT ─── */
.wr-article-foot{
  margin-top:56px;padding:36px 0 88px;
  border-top:1px solid rgba(255,255,255,0.06);
  display:flex;flex-direction:column;gap:36px;
}
.wr-post-footer-link{
  display:inline-flex;align-items:center;gap:10px;
  font-family:var(--font-mono);font-size:10px;letter-spacing:0.14em;
  text-transform:uppercase;color:var(--gold);
  text-decoration:none;transition:gap 0.3s;align-self:flex-start;
}
.wr-post-footer-link:hover{gap:16px}
.wr-post-footer-link::after{
  content:'';display:block;width:20px;height:1px;background:var(--gold);
  transition:width 0.3s var(--ease-out);
}
.wr-post-footer-link:hover::after{width:32px}

/* ─── CTA ─── */
#wr-cta{
  padding:80px 56px;background:#0d0d14;text-align:center;
  border-top:1px solid rgba(255,255,255,0.04);
}
.wr-cta-eyebrow{
  font-family:var(--font-mono);font-size:10px;letter-spacing:0.22em;
  text-transform:uppercase;color:var(--gold);margin-bottom:24px;
  display:flex;align-items:center;justify-content:center;gap:16px;
}
.wr-cta-eyebrow::before,.wr-cta-eyebrow::after{
  content:'';display:block;width:40px;height:1px;background:var(--gold);opacity:0.4;
}
.wr-cta-text{
  font-family:var(--font-display);font-size:clamp(32px,5vw,56px);
  font-weight:300;color:var(--paper);line-height:1.05;margin-bottom:32px;
}
.wr-cta-text em{font-style:italic;color:var(--gold)}
.wr-btn-primary{
  display:inline-flex;align-items:center;gap:10px;
  padding:16px 36px;background:var(--gold);color:var(--charcoal);
  font-size:11px;font-weight:500;letter-spacing:0.14em;
  text-transform:uppercase;text-decoration:none;border-radius:2px;
  font-family:var(--font-mono);transition:background 0.25s,transform 0.2s;
}
.wr-btn-primary:hover{background:var(--gold-light);transform:translateY(-1px)}
@media(max-width:640px){#wr-article{padding:140px 24px 0}#wr-cta{padding:64px 28px}}
""".strip()

PAGE_JS = """
/* Scroll progress */
var bar=document.getElementById('wr-progress');
window.addEventListener('scroll',function(){
  var d=document.documentElement;
  var s=d.scrollTop||document.body.scrollTop;
  var t=d.scrollHeight-d.clientHeight;
  bar.style.width=(t>0?(s/t)*100:0)+'%';
},{passive:true});
/* Copy link */
document.querySelectorAll('.wr-copy-btn').forEach(function(btn){
  btn.addEventListener('click',function(){
    var url=btn.getAttribute('data-url');
    function done(){
      var label=btn.querySelector('span');
      var old=label.textContent;
      label.textContent='Copied';
      setTimeout(function(){label.textContent=old;},1600);
    }
    if(navigator.clipboard&&navigator.clipboard.writeText){
      navigator.clipboard.writeText(url).then(done,function(){window.prompt('Copy this link:',url);});
    }else{window.prompt('Copy this link:',url);}
  });
});
""".strip()


def render_post_page(post: dict) -> str:
    url = post_url(post)
    title = esc(post["title"])
    excerpt = esc(post["excerpt"])
    image = esc(post["image"])
    share = share_bar(post)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
{FINGERPRINT}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title} — Wil Randolph</title>
<meta name="description" content="{excerpt}">
<meta name="author" content="Wil Randolph">
<link rel="canonical" href="{esc(url)}">
<meta property="og:type" content="article">
<meta property="og:site_name" content="Wil Randolph — Brand &amp; Marketing Strategist">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{excerpt}">
<meta property="og:url" content="{esc(url)}">
<meta property="og:image" content="{image}">
<meta property="article:published_time" content="{esc(post['date'])}">
<meta property="article:author" content="Wil Randolph">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{title}">
<meta name="twitter:description" content="{excerpt}">
<meta name="twitter:image" content="{image}">
<script type="application/ld+json">
{json_ld(post)}
</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,600;1,300;1,400&family=DM+Sans:wght@300;400;500&family=DM+Mono:wght@300;400&display=swap" rel="stylesheet">
<style>
{PAGE_CSS}
</style>
</head>
<body>

<nav id="wr-nav">
  <a href="../index.html" class="wr-nav-brand">
    <span class="wr-nav-name">Wil Randolph</span>
    <span class="wr-nav-sub">Brand &amp; Marketing Strategist</span>
  </a>
  <div class="wr-nav-links">
    <a href="../index.html">Strategy</a>
    <span class="wr-nav-div"></span>
    <a href="../work.html">Work</a>
    <span class="wr-nav-div"></span>
    <a href="../cases.html">Case Studies</a>
    <span class="wr-nav-div"></span>
    <a href="../about.html">About</a>
    <span class="wr-nav-div"></span>
    <a href="../journal.html" class="active">Journal</a>
    <span class="wr-nav-div"></span>
    <a href="../contact.html">Contact</a>
  </div>
</nav>

<div id="wr-progress"></div>

<article id="wr-article">
  <header class="wr-article-head">
    <a href="../journal.html" class="wr-back">Journal</a>
    <div class="wr-article-cats">{cat_tags(post)}</div>
    <h1 class="wr-article-title">{title}</h1>
    <div class="wr-article-meta"><span>Wil Randolph</span><span class="wr-meta-dot"></span><span>{esc(post['dateDisplay'])}</span></div>
    {share}
  </header>
  <div class="wr-article-hero"><img src="{image}" alt="{title}" loading="eager"></div>
  <div class="wr-article-body">{post['body']}</div>
  <footer class="wr-article-foot">
    {share}
    <a href="../journal.html" class="wr-post-footer-link">Back to the Journal</a>
  </footer>
</article>

<section id="wr-cta">
  <div class="wr-cta-eyebrow">Open to Roles &amp; Select Engagements</div>
  <p class="wr-cta-text">Ready to put this<br>thinking to <em>work for you?</em></p>
  <a href="../contact.html" class="wr-btn-primary">Start a Conversation &rarr;</a>
</section>

<script>
{PAGE_JS}
</script>
</body>
</html>
"""


def rewrite_journal_html(posts: list) -> None:
    """Regenerate the POSTS data block and OG meta block inside journal.html."""
    path = ROOT / "journal.html"
    src = path.read_text(encoding="utf-8")

    posts_js = json.dumps(posts, indent=2, ensure_ascii=False).replace("</", "<\\/")
    block = f"/* POSTS:BEGIN — generated from posts.json by build_journal.py. Do not edit by hand. */\nvar POSTS = {posts_js};\n/* POSTS:END */"
    new = re.sub(
        r"/\* POSTS:BEGIN[\s\S]*?/\* POSTS:END \*/",
        lambda _: block,
        src,
        count=1,
    )
    if new == src and "/* POSTS:BEGIN" not in src:
        sys.exit("ERROR: POSTS:BEGIN/END markers not found in journal.html")

    latest = posts[0]
    og = (
        "<!-- OG:BEGIN — generated by build_journal.py -->\n"
        '<meta property="og:type" content="website">\n'
        '<meta property="og:site_name" content="Wil Randolph — Brand &amp; Marketing Strategist">\n'
        '<meta property="og:title" content="Journal — Wil Randolph">\n'
        '<meta property="og:description" content="Writing on brand strategy, marketing practice, creative leadership, AEC marketing, AI integration, and the business of building things that last.">\n'
        f'<meta property="og:url" content="{SITE_URL}/journal.html">\n'
        f'<meta property="og:image" content="{esc(latest["image"])}">\n'
        '<meta name="twitter:card" content="summary_large_image">\n'
        "<!-- OG:END -->"
    )
    new2 = re.sub(r"<!-- OG:BEGIN[\s\S]*?<!-- OG:END -->", lambda _: og, new, count=1)
    if new2 == new and "<!-- OG:BEGIN" not in new:
        sys.exit("ERROR: OG:BEGIN/END markers not found in journal.html")

    path.write_text(new2, encoding="utf-8")


def main() -> None:
    posts = json.loads((ROOT / "posts.json").read_text(encoding="utf-8"))
    if not posts:
        sys.exit("ERROR: posts.json is empty")

    seen = set()
    for p in posts:
        for field in ("id", "title", "date", "dateDisplay", "categories", "image", "excerpt", "body"):
            if field not in p:
                sys.exit(f"ERROR: post '{p.get('id', '?')}' is missing field '{field}'")
        if p["id"] in seen:
            sys.exit(f"ERROR: duplicate post id '{p['id']}'")
        seen.add(p["id"])
        if not p["image"]:
            print(f"WARNING: post '{p['id']}' has no image — social previews will have no picture")

    JOURNAL_DIR.mkdir(exist_ok=True)

    for p in posts:
        (JOURNAL_DIR / f"{p['id']}.html").write_text(render_post_page(p), encoding="utf-8")
    print(f"Generated {len(posts)} post pages in journal/")

    # Remove stale generated pages for posts no longer in posts.json
    for f in JOURNAL_DIR.glob("*.html"):
        if f.stem not in seen and FINGERPRINT in f.read_text(encoding="utf-8"):
            f.unlink()
            print(f"Removed stale page journal/{f.name}")

    rewrite_journal_html(posts)
    print("Updated journal.html (POSTS data + OG meta)")
    print("Done. Commit and push to GitHub — Vercel deploys automatically.")


if __name__ == "__main__":
    main()
